### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by ghost** [donRaphaco/neotex#4]
Hi, 
i installed neotex via a package manager, and upon opening a .tex file i get the error:

Error detected while processing .../tex.vim:
line 20:
E117: Unknown function: _neotex_init

I looked through the code but unfortunately i know nothing about vimscript or how nvim handles the call to python.
Any help would be appreciated, thanks.

// edit: user error :x

**Comment by rnorris7756** [comment]
I am having the same issue.  Can you post what you did to solve this issue?

**Comment by ghost** [comment]
I forgot to
"Do :UpdateRemotePlugins after installing or updating!"
See Installation section in the readme.

**Comment by rnorris7756** [comment]
I actually have done that part, so I must be running into a different issue.

**Comment by boardfish** [comment]
Just ran :PluginUpdate and :UpdateRemotePlugins, same result.
