### ISSUE TITLE
Setting g:neotex_delay delays other neovim plugins

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [donRaphaco/neotex#5]
Specifically [deoplete](https://github.com/Shougo/deoplete.nvim). Completions don't show up until 5 seconds after typing when g:neotex_delay is set to 5000
Deoplete resumes normal behavior after calling `:NeoTexOff`

**Comment by donRaphaco** [comment]
Sorry it took so long, but a56c5db0fd495f6fe41627cd14af44de0fa3816a finally fixes this.
