### ISSUE TITLE
Unable to install on Debian Stretch, NeoVim v0.2.3-781-gc21cf6d3c

### ISSUE THREAD

**Issue by JayBusch** [donRaphaco/neotex#7]
Followed instructions to use vim-plug to install.

The NeoTex command is unavailable.

also have the following in init.vim:

let g:neotex_enabled = 2

Any help appreciated; would really like to get down to editing LaTeX in NeoVim.

**Comment by donRaphaco** [comment]
Did you use a plugin manager? Which one?
The NeoTex command should only be available when a .tex file is opened.

**Comment by JayBusch** [comment]
Vim-Plug

https://github.com/junegunn/vim-plug

I was testing with a new file called "test.tex" by using the  "nvim test.tex" command from my user's home directory.

**Comment by donRaphaco** [comment]
Are you sure you did `:PlugInstall`?
Can you check if `neotex/ftplugin/tex.vim` exists inside your vim-plug plugin folder
(location depends on configuration in init.vim e.g. `call plug#begin('~/.vim/plugged')`, default is `~/.config/nvim/plugged`)

**Comment by JayBusch** [comment]
I did do :PlugInstall yes.

This file exists (jbusch is my username):  /home/jbusch/.config/nvim/plugged/neotex/ftplugin/tex.vim

The Vim-Plug potion of my init.vim looks like this:

"colorscheme darkblue
"call plug#begin('~/.config/nvim/autoload/plugged')
call plug#begin('~/.config/nvim/plugged')
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-git'
"Plug 'critiqjo/lldb.nvim'
Plug 'scrooloose/nerdtree'
Plug 'https://github.com/benmills/vimux.git'
Plug 'https://github.com/jalcine/cmake.vim.git'
Plug 'https://github.com/rhysd/vim-clang-format.git'
Plug 'https://github.com/Shougo/deoplete.nvim'
Plug 'https://github.com/myitcv/neogo'
Plug 'https://github.com/fatih/vim-go'
Plug 'https://github.com/mattn/emmet-vim'
Plug 'chrisbra/csv.vim'
Plug 'godlygeek/tabular'
Plug 'vim-airline/vim-airline'
Plug 'itchyny/calendar.vim'
"Plug 'xuhdev/vim-latex-live-preview', { 'for': 'tex' }
"Plug 'lervag/vimtex'
Plug 'donRaphaco/neotex', { 'for': 'tex' }
call plug#end()

**Comment by donRaphaco** [comment]
Ok, i think i know what the problem is now.
You did everything right, but you should add `let g:tex_flavor = "latex"` to your config.
The problem is that vim by default tries to guess the filetype of .tex files and with empty files it sets the filetype to `plaintex` and the plugin isn't loaded.
See `:h tex_flavor` for more details.
I think I should mention this in the Readme aswell.
